// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package user

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//   - UserLoginId
//   - UserName
//   - Password
type UserLoginRequest struct {
	UserLoginId *int64 `thrift:"userLoginId,1" db:"userLoginId" json:"userLoginId,omitempty"`
	UserName    string `thrift:"userName,2,required" db:"userName" json:"userName"`
	Password    string `thrift:"password,3,required" db:"password" json:"password"`
}

func NewUserLoginRequest() *UserLoginRequest {
	return &UserLoginRequest{}
}

var UserLoginRequest_UserLoginId_DEFAULT int64

func (p *UserLoginRequest) GetUserLoginId() int64 {
	if !p.IsSetUserLoginId() {
		return UserLoginRequest_UserLoginId_DEFAULT
	}
	return *p.UserLoginId
}

func (p *UserLoginRequest) GetUserName() string {
	return p.UserName
}

func (p *UserLoginRequest) GetPassword() string {
	return p.Password
}

func (p *UserLoginRequest) IsSetUserLoginId() bool {
	return p.UserLoginId != nil
}

func (p *UserLoginRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetUserName bool = false
	var issetPassword bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetUserName = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
				issetPassword = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetUserName {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field UserName is not set"))
	}
	if !issetPassword {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Password is not set"))
	}
	return nil
}

func (p *UserLoginRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.UserLoginId = &v
	}
	return nil
}

func (p *UserLoginRequest) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.UserName = v
	}
	return nil
}

func (p *UserLoginRequest) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Password = v
	}
	return nil
}

func (p *UserLoginRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "UserLoginRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserLoginRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetUserLoginId() {
		if err := oprot.WriteFieldBegin(ctx, "userLoginId", thrift.I64, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:userLoginId: ", p), err)
		}
		if err := oprot.WriteI64(ctx, int64(*p.UserLoginId)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.userLoginId (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:userLoginId: ", p), err)
		}
	}
	return err
}

func (p *UserLoginRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "userName", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:userName: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.UserName)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.userName (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:userName: ", p), err)
	}
	return err
}

func (p *UserLoginRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "password", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:password: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Password)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.password (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:password: ", p), err)
	}
	return err
}

func (p *UserLoginRequest) Equals(other *UserLoginRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.UserLoginId != other.UserLoginId {
		if p.UserLoginId == nil || other.UserLoginId == nil {
			return false
		}
		if (*p.UserLoginId) != (*other.UserLoginId) {
			return false
		}
	}
	if p.UserName != other.UserName {
		return false
	}
	if p.Password != other.Password {
		return false
	}
	return true
}

func (p *UserLoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserLoginRequest(%+v)", *p)
}

func (p *UserLoginRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*user.UserLoginRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserLoginRequest)(nil)

func (p *UserLoginRequest) Validate() error {
	return nil
}

// Attributes:
//   - UserLoginId
//   - UserName
//   - Password
//   - UserInfoId
//   - RealName
//   - Phone
//   - Email
//   - Gender
//   - Birthday
//   - CreateTime
//   - UpdateTime
type UserResponse struct {
	UserLoginId *int64  `thrift:"userLoginId,1" db:"userLoginId" json:"userLoginId,omitempty"`
	UserName    *string `thrift:"userName,2" db:"userName" json:"userName,omitempty"`
	Password    *string `thrift:"password,3" db:"password" json:"password,omitempty"`
	UserInfoId  *int64  `thrift:"userInfoId,4" db:"userInfoId" json:"userInfoId,omitempty"`
	RealName    *string `thrift:"realName,5" db:"realName" json:"realName,omitempty"`
	Phone       *string `thrift:"phone,6" db:"phone" json:"phone,omitempty"`
	Email       *string `thrift:"email,7" db:"email" json:"email,omitempty"`
	Gender      *int8   `thrift:"gender,8" db:"gender" json:"gender,omitempty"`
	Birthday    *string `thrift:"birthday,9" db:"birthday" json:"birthday,omitempty"`
	CreateTime  *string `thrift:"createTime,10" db:"createTime" json:"createTime,omitempty"`
	UpdateTime  *string `thrift:"updateTime,11" db:"updateTime" json:"updateTime,omitempty"`
}

func NewUserResponse() *UserResponse {
	return &UserResponse{}
}

var UserResponse_UserLoginId_DEFAULT int64

func (p *UserResponse) GetUserLoginId() int64 {
	if !p.IsSetUserLoginId() {
		return UserResponse_UserLoginId_DEFAULT
	}
	return *p.UserLoginId
}

var UserResponse_UserName_DEFAULT string

func (p *UserResponse) GetUserName() string {
	if !p.IsSetUserName() {
		return UserResponse_UserName_DEFAULT
	}
	return *p.UserName
}

var UserResponse_Password_DEFAULT string

func (p *UserResponse) GetPassword() string {
	if !p.IsSetPassword() {
		return UserResponse_Password_DEFAULT
	}
	return *p.Password
}

var UserResponse_UserInfoId_DEFAULT int64

func (p *UserResponse) GetUserInfoId() int64 {
	if !p.IsSetUserInfoId() {
		return UserResponse_UserInfoId_DEFAULT
	}
	return *p.UserInfoId
}

var UserResponse_RealName_DEFAULT string

func (p *UserResponse) GetRealName() string {
	if !p.IsSetRealName() {
		return UserResponse_RealName_DEFAULT
	}
	return *p.RealName
}

var UserResponse_Phone_DEFAULT string

func (p *UserResponse) GetPhone() string {
	if !p.IsSetPhone() {
		return UserResponse_Phone_DEFAULT
	}
	return *p.Phone
}

var UserResponse_Email_DEFAULT string

func (p *UserResponse) GetEmail() string {
	if !p.IsSetEmail() {
		return UserResponse_Email_DEFAULT
	}
	return *p.Email
}

var UserResponse_Gender_DEFAULT int8

func (p *UserResponse) GetGender() int8 {
	if !p.IsSetGender() {
		return UserResponse_Gender_DEFAULT
	}
	return *p.Gender
}

var UserResponse_Birthday_DEFAULT string

func (p *UserResponse) GetBirthday() string {
	if !p.IsSetBirthday() {
		return UserResponse_Birthday_DEFAULT
	}
	return *p.Birthday
}

var UserResponse_CreateTime_DEFAULT string

func (p *UserResponse) GetCreateTime() string {
	if !p.IsSetCreateTime() {
		return UserResponse_CreateTime_DEFAULT
	}
	return *p.CreateTime
}

var UserResponse_UpdateTime_DEFAULT string

func (p *UserResponse) GetUpdateTime() string {
	if !p.IsSetUpdateTime() {
		return UserResponse_UpdateTime_DEFAULT
	}
	return *p.UpdateTime
}

func (p *UserResponse) IsSetUserLoginId() bool {
	return p.UserLoginId != nil
}

func (p *UserResponse) IsSetUserName() bool {
	return p.UserName != nil
}

func (p *UserResponse) IsSetPassword() bool {
	return p.Password != nil
}

func (p *UserResponse) IsSetUserInfoId() bool {
	return p.UserInfoId != nil
}

func (p *UserResponse) IsSetRealName() bool {
	return p.RealName != nil
}

func (p *UserResponse) IsSetPhone() bool {
	return p.Phone != nil
}

func (p *UserResponse) IsSetEmail() bool {
	return p.Email != nil
}

func (p *UserResponse) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UserResponse) IsSetBirthday() bool {
	return p.Birthday != nil
}

func (p *UserResponse) IsSetCreateTime() bool {
	return p.CreateTime != nil
}

func (p *UserResponse) IsSetUpdateTime() bool {
	return p.UpdateTime != nil
}

func (p *UserResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.BYTE {
				if err := p.ReadField8(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 9:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField9(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 10:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField10(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 11:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField11(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.UserLoginId = &v
	}
	return nil
}

func (p *UserResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.UserName = &v
	}
	return nil
}

func (p *UserResponse) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Password = &v
	}
	return nil
}

func (p *UserResponse) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.UserInfoId = &v
	}
	return nil
}

func (p *UserResponse) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.RealName = &v
	}
	return nil
}

func (p *UserResponse) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.Phone = &v
	}
	return nil
}

func (p *UserResponse) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.Email = &v
	}
	return nil
}

func (p *UserResponse) ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadByte(ctx); err != nil {
		return thrift.PrependError("error reading field 8: ", err)
	} else {
		temp := int8(v)
		p.Gender = &temp
	}
	return nil
}

func (p *UserResponse) ReadField9(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 9: ", err)
	} else {
		p.Birthday = &v
	}
	return nil
}

func (p *UserResponse) ReadField10(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.CreateTime = &v
	}
	return nil
}

func (p *UserResponse) ReadField11(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 11: ", err)
	} else {
		p.UpdateTime = &v
	}
	return nil
}

func (p *UserResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "UserResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField5(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField6(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField7(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField8(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField9(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField10(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField11(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetUserLoginId() {
		if err := oprot.WriteFieldBegin(ctx, "userLoginId", thrift.I64, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:userLoginId: ", p), err)
		}
		if err := oprot.WriteI64(ctx, int64(*p.UserLoginId)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.userLoginId (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:userLoginId: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetUserName() {
		if err := oprot.WriteFieldBegin(ctx, "userName", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:userName: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.UserName)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.userName (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:userName: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetPassword() {
		if err := oprot.WriteFieldBegin(ctx, "password", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:password: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Password)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.password (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:password: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetUserInfoId() {
		if err := oprot.WriteFieldBegin(ctx, "userInfoId", thrift.I64, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:userInfoId: ", p), err)
		}
		if err := oprot.WriteI64(ctx, int64(*p.UserInfoId)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.userInfoId (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:userInfoId: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetRealName() {
		if err := oprot.WriteFieldBegin(ctx, "realName", thrift.STRING, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:realName: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.RealName)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.realName (5) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:realName: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetPhone() {
		if err := oprot.WriteFieldBegin(ctx, "phone", thrift.STRING, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:phone: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Phone)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.phone (6) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:phone: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetEmail() {
		if err := oprot.WriteFieldBegin(ctx, "email", thrift.STRING, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:email: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Email)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.email (7) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:email: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetGender() {
		if err := oprot.WriteFieldBegin(ctx, "gender", thrift.BYTE, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:gender: ", p), err)
		}
		if err := oprot.WriteByte(ctx, int8(*p.Gender)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.gender (8) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:gender: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField9(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetBirthday() {
		if err := oprot.WriteFieldBegin(ctx, "birthday", thrift.STRING, 9); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:birthday: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Birthday)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.birthday (9) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 9:birthday: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField10(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetCreateTime() {
		if err := oprot.WriteFieldBegin(ctx, "createTime", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:createTime: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.CreateTime)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.createTime (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:createTime: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) writeField11(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetUpdateTime() {
		if err := oprot.WriteFieldBegin(ctx, "updateTime", thrift.STRING, 11); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 11:updateTime: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.UpdateTime)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.updateTime (11) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 11:updateTime: ", p), err)
		}
	}
	return err
}

func (p *UserResponse) Equals(other *UserResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.UserLoginId != other.UserLoginId {
		if p.UserLoginId == nil || other.UserLoginId == nil {
			return false
		}
		if (*p.UserLoginId) != (*other.UserLoginId) {
			return false
		}
	}
	if p.UserName != other.UserName {
		if p.UserName == nil || other.UserName == nil {
			return false
		}
		if (*p.UserName) != (*other.UserName) {
			return false
		}
	}
	if p.Password != other.Password {
		if p.Password == nil || other.Password == nil {
			return false
		}
		if (*p.Password) != (*other.Password) {
			return false
		}
	}
	if p.UserInfoId != other.UserInfoId {
		if p.UserInfoId == nil || other.UserInfoId == nil {
			return false
		}
		if (*p.UserInfoId) != (*other.UserInfoId) {
			return false
		}
	}
	if p.RealName != other.RealName {
		if p.RealName == nil || other.RealName == nil {
			return false
		}
		if (*p.RealName) != (*other.RealName) {
			return false
		}
	}
	if p.Phone != other.Phone {
		if p.Phone == nil || other.Phone == nil {
			return false
		}
		if (*p.Phone) != (*other.Phone) {
			return false
		}
	}
	if p.Email != other.Email {
		if p.Email == nil || other.Email == nil {
			return false
		}
		if (*p.Email) != (*other.Email) {
			return false
		}
	}
	if p.Gender != other.Gender {
		if p.Gender == nil || other.Gender == nil {
			return false
		}
		if (*p.Gender) != (*other.Gender) {
			return false
		}
	}
	if p.Birthday != other.Birthday {
		if p.Birthday == nil || other.Birthday == nil {
			return false
		}
		if (*p.Birthday) != (*other.Birthday) {
			return false
		}
	}
	if p.CreateTime != other.CreateTime {
		if p.CreateTime == nil || other.CreateTime == nil {
			return false
		}
		if (*p.CreateTime) != (*other.CreateTime) {
			return false
		}
	}
	if p.UpdateTime != other.UpdateTime {
		if p.UpdateTime == nil || other.UpdateTime == nil {
			return false
		}
		if (*p.UpdateTime) != (*other.UpdateTime) {
			return false
		}
	}
	return true
}

func (p *UserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserResponse(%+v)", *p)
}

func (p *UserResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*user.UserResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserResponse)(nil)

func (p *UserResponse) Validate() error {
	return nil
}

// Attributes:
//   - Message
//   - Code
type LoginException struct {
	Message string `thrift:"message,1,required" db:"message" json:"message"`
	Code    *int32 `thrift:"code,2" db:"code" json:"code,omitempty"`
}

func NewLoginException() *LoginException {
	return &LoginException{}
}

func (p *LoginException) GetMessage() string {
	return p.Message
}

var LoginException_Code_DEFAULT int32

func (p *LoginException) GetCode() int32 {
	if !p.IsSetCode() {
		return LoginException_Code_DEFAULT
	}
	return *p.Code
}

func (p *LoginException) IsSetCode() bool {
	return p.Code != nil
}

func (p *LoginException) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetMessage bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetMessage = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetMessage {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Message is not set"))
	}
	return nil
}

func (p *LoginException) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Message = v
	}
	return nil
}

func (p *LoginException) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Code = &v
	}
	return nil
}

func (p *LoginException) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "LoginException"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *LoginException) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "message", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:message: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Message)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.message (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:message: ", p), err)
	}
	return err
}

func (p *LoginException) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetCode() {
		if err := oprot.WriteFieldBegin(ctx, "code", thrift.I32, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:code: ", p), err)
		}
		if err := oprot.WriteI32(ctx, int32(*p.Code)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.code (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:code: ", p), err)
		}
	}
	return err
}

func (p *LoginException) Equals(other *LoginException) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Message != other.Message {
		return false
	}
	if p.Code != other.Code {
		if p.Code == nil || other.Code == nil {
			return false
		}
		if (*p.Code) != (*other.Code) {
			return false
		}
	}
	return true
}

func (p *LoginException) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginException(%+v)", *p)
}

func (p *LoginException) Error() string {
	return p.String()
}

func (LoginException) TExceptionType() thrift.TExceptionType {
	return thrift.TExceptionTypeCompiled
}

var _ thrift.TException = (*LoginException)(nil)

func (p *LoginException) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*user.LoginException",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*LoginException)(nil)

func (p *LoginException) Validate() error {
	return nil
}

type UserService interface {
	// Parameters:
	//  - Request
	//
	Login(ctx context.Context, request *UserLoginRequest) (_r *UserResponse, _err error)
}

type UserServiceClient struct {
	c    thrift.TClient
	meta thrift.ResponseMeta
}

func NewUserServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *UserServiceClient {
	return &UserServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewUserServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *UserServiceClient {
	return &UserServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewUserServiceClient(c thrift.TClient) *UserServiceClient {
	return &UserServiceClient{
		c: c,
	}
}

func (p *UserServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *UserServiceClient) LastResponseMeta_() thrift.ResponseMeta {
	return p.meta
}

func (p *UserServiceClient) SetLastResponseMeta_(meta thrift.ResponseMeta) {
	p.meta = meta
}

// Parameters:
//   - Request
func (p *UserServiceClient) Login(ctx context.Context, request *UserLoginRequest) (_r *UserResponse, _err error) {
	var _args0 UserServiceLoginArgs
	_args0.Request = request
	var _result2 UserServiceLoginResult
	var _meta1 thrift.ResponseMeta
	_meta1, _err = p.Client_().Call(ctx, "login", &_args0, &_result2)
	p.SetLastResponseMeta_(_meta1)
	if _err != nil {
		return
	}
	switch {
	case _result2.Ex != nil:
		return _r, _result2.Ex
	}

	if _ret3 := _result2.GetSuccess(); _ret3 != nil {
		return _ret3, nil
	}
	return nil, thrift.NewTApplicationException(thrift.MISSING_RESULT, "login failed: unknown result")
}

type UserServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      UserService
}

func (p *UserServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *UserServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *UserServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewUserServiceProcessor(handler UserService) *UserServiceProcessor {

	self4 := &UserServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self4.processorMap["login"] = &userServiceProcessorLogin{handler: handler}
	return self4
}

func (p *UserServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err2 := iprot.ReadMessageBegin(ctx)
	if err2 != nil {
		return false, thrift.WrapTException(err2)
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(ctx, thrift.STRUCT)
	iprot.ReadMessageEnd(ctx)
	x5 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(ctx, name, thrift.EXCEPTION, seqId)
	x5.Write(ctx, oprot)
	oprot.WriteMessageEnd(ctx)
	oprot.Flush(ctx)
	return false, x5
}

type userServiceProcessorLogin struct {
	handler UserService
}

func (p *userServiceProcessorLogin) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	var _write_err6 thrift.TException
	args := UserServiceLoginArgs{}
	if err2 := args.Read(ctx, iprot); err2 != nil {
		iprot.ReadMessageEnd(ctx)
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err2.Error())
		oprot.WriteMessageBegin(ctx, "login", thrift.EXCEPTION, seqId)
		x.Write(ctx, oprot)
		oprot.WriteMessageEnd(ctx)
		oprot.Flush(ctx)
		return false, thrift.WrapTException(err2)
	}
	iprot.ReadMessageEnd(ctx)

	tickerCancel := func() {}
	// Start a goroutine to do server side connectivity check.
	if thrift.ServerConnectivityCheckInterval > 0 {
		var cancel context.CancelCauseFunc
		ctx, cancel = context.WithCancelCause(ctx)
		defer cancel(nil)
		var tickerCtx context.Context
		tickerCtx, tickerCancel = context.WithCancel(context.Background())
		defer tickerCancel()
		go func(ctx context.Context, cancel context.CancelCauseFunc) {
			ticker := time.NewTicker(thrift.ServerConnectivityCheckInterval)
			defer ticker.Stop()
			for {
				select {
				case <-ctx.Done():
					return
				case <-ticker.C:
					if !iprot.Transport().IsOpen() {
						cancel(thrift.ErrAbandonRequest)
						return
					}
				}
			}
		}(tickerCtx, cancel)
	}

	result := UserServiceLoginResult{}
	if retval, err2 := p.handler.Login(ctx, args.Request); err2 != nil {
		tickerCancel()
		err = thrift.WrapTException(err2)
		switch v := err2.(type) {
		case *LoginException:
			result.Ex = v
		default:
			if errors.Is(err2, thrift.ErrAbandonRequest) {
				return false, &thrift.ProcessorError{
					WriteError:    thrift.WrapTException(err2),
					EndpointError: err,
				}
			}
			if errors.Is(err2, context.Canceled) {
				if err3 := context.Cause(ctx); errors.Is(err3, thrift.ErrAbandonRequest) {
					return false, &thrift.ProcessorError{
						WriteError:    thrift.WrapTException(err3),
						EndpointError: err,
					}
				}
			}
			_exc7 := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing login: "+err2.Error())
			if err2 := oprot.WriteMessageBegin(ctx, "login", thrift.EXCEPTION, seqId); err2 != nil {
				_write_err6 = thrift.WrapTException(err2)
			}
			if err2 := _exc7.Write(ctx, oprot); _write_err6 == nil && err2 != nil {
				_write_err6 = thrift.WrapTException(err2)
			}
			if err2 := oprot.WriteMessageEnd(ctx); _write_err6 == nil && err2 != nil {
				_write_err6 = thrift.WrapTException(err2)
			}
			if err2 := oprot.Flush(ctx); _write_err6 == nil && err2 != nil {
				_write_err6 = thrift.WrapTException(err2)
			}
			if _write_err6 != nil {
				return false, &thrift.ProcessorError{
					WriteError:    _write_err6,
					EndpointError: err,
				}
			}
			return true, err
		}
	} else {
		result.Success = retval
	}
	tickerCancel()
	if err2 := oprot.WriteMessageBegin(ctx, "login", thrift.REPLY, seqId); err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if err2 := result.Write(ctx, oprot); _write_err6 == nil && err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if err2 := oprot.WriteMessageEnd(ctx); _write_err6 == nil && err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if err2 := oprot.Flush(ctx); _write_err6 == nil && err2 != nil {
		_write_err6 = thrift.WrapTException(err2)
	}
	if _write_err6 != nil {
		return false, &thrift.ProcessorError{
			WriteError:    _write_err6,
			EndpointError: err,
		}
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//   - Request
type UserServiceLoginArgs struct {
	Request *UserLoginRequest `thrift:"request,1" db:"request" json:"request"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

var UserServiceLoginArgs_Request_DEFAULT *UserLoginRequest

func (p *UserServiceLoginArgs) GetRequest() *UserLoginRequest {
	if !p.IsSetRequest() {
		return UserServiceLoginArgs_Request_DEFAULT
	}
	return p.Request
}

func (p *UserServiceLoginArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *UserServiceLoginArgs) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserServiceLoginArgs) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Request = &UserLoginRequest{}
	if err := p.Request.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Request), err)
	}
	return nil
}

func (p *UserServiceLoginArgs) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "login_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserServiceLoginArgs) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "request", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:request: ", p), err)
	}
	if err := p.Request.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Request), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:request: ", p), err)
	}
	return err
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

func (p *UserServiceLoginArgs) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*user.UserServiceLoginArgs",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserServiceLoginArgs)(nil)

// Attributes:
//   - Success
//   - Ex
type UserServiceLoginResult struct {
	Success *UserResponse   `thrift:"success,0" db:"success" json:"success,omitempty"`
	Ex      *LoginException `thrift:"ex,1" db:"ex" json:"ex,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

var UserServiceLoginResult_Success_DEFAULT *UserResponse

func (p *UserServiceLoginResult) GetSuccess() *UserResponse {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}

var UserServiceLoginResult_Ex_DEFAULT *LoginException

func (p *UserServiceLoginResult) GetEx() *LoginException {
	if !p.IsSetEx() {
		return UserServiceLoginResult_Ex_DEFAULT
	}
	return p.Ex
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) IsSetEx() bool {
	return p.Ex != nil
}

func (p *UserServiceLoginResult) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField0(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *UserServiceLoginResult) ReadField0(ctx context.Context, iprot thrift.TProtocol) error {
	p.Success = &UserResponse{}
	if err := p.Success.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *UserServiceLoginResult) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.Ex = &LoginException{}
	if err := p.Ex.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ex), err)
	}
	return nil
}

func (p *UserServiceLoginResult) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "login_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField0(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UserServiceLoginResult) writeField0(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin(ctx, "success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *UserServiceLoginResult) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetEx() {
		if err := oprot.WriteFieldBegin(ctx, "ex", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ex: ", p), err)
		}
		if err := p.Ex.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ex), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ex: ", p), err)
		}
	}
	return err
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

func (p *UserServiceLoginResult) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*user.UserServiceLoginResult",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UserServiceLoginResult)(nil)
